services:
  worker:
    image: dairoot/chatgpt-mirror:latest
    volumes:
      - ./admin/dist:/tmp/dist
      - chatgpt_data:/app/worker/.wrangler

    ports:
      - "50001-50002:50001"
    deploy:
      replicas: 2
    restart: always

volumes:
  chatgpt_data:
